//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationASP452MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTable
    {
        public byte ID { get; set; }
        public string Name { get; set; }
        public byte Age { get; set; }
        public System.DateTime DOB { get; set; }
        public string Petname { get; set; }
    }
}
