//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTable
    {
        public int CatID { get; set; }
        public int OwnerID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    
        public virtual OwnerTable OwnerTable { get; set; }
        public virtual CatTable_SiameseTable CatTable_SiameseTable { get; set; }
    }
}
