//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTable_SiameseTable
    {
        public int Attitude { get; set; }
        public int CatID { get; set; }
        public int OwnerTable1_OwnerID { get; set; }
    
        public virtual CatTable CatTable { get; set; }
        public virtual OwnerTable OwnerTable { get; set; }
    }
}
