//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerTable
    {
        public OwnerTable()
        {
            this.CatTable = new HashSet<CatTable>();
            this.CatTable_SiameseTable = new HashSet<CatTable_SiameseTable>();
        }
    
        public int OwnerID { get; set; }
        public string Ownername { get; set; }
    
        public virtual ICollection<CatTable> CatTable { get; set; }
        public virtual ICollection<CatTable_SiameseTable> CatTable_SiameseTable { get; set; }
    }
}
